version: '3.8'

services:
  mongodb_v1:
    image: mongo:latest
    container_name: mongodb_v1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_v1:/data/db

  mongodb_v2:
    image: mongo:latest
    container_name: mongodb_v2
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_v2:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data_v1:
  mongodb_data_v2:
  postgres_data:
